# Generated by Django 5.1.6 on 2025-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_receiptdetail_options_receiptdetail_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='subtotal',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
