# Generated by Django 5.1.6 on 2025-04-01 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, null=True),
        ),
    ]
