# Generated by Django 5.1.6 on 2025-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_supplier_receipt_receiptdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdetail',
            name='unit_price',
            field=models.FloatField(default=1),
        ),
    ]
