# Generated by Django 5.1.6 on 2025-03-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_receiptdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptdetail',
            options={'verbose_name': 'Receipt Detail', 'verbose_name_plural': 'Receipt Details'},
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptdetail',
            unique_together={('receipt', 'product')},
        ),
    ]
